version: '3.7'

services:
 web: 
  build: 				            # because we are not using default Dockerfile, we specify file  as below
   context: .
   dockerfile: Dockerfile.dev
  ports:
   - "3000:3000"
  volumes:
   - /app/node_modules 		# for directories inside containers we need to run app
   - ./:/app					      # every other directory
 tests:           # everything is same, except we don't need a port and we override the command
  build: 		
   context: .
   dockerfile: Dockerfile.dev
  volumes:
   - /app/node_modules
   - ./:/app
  command: ["npm", "run", "test"]    #override default command